config/routes.rb
Rails.application.routes.draw do

  devise_for :consumers
  root to: "consumers#new"

  get '/favorites/new',      :controller => 'favorites', :action => 'new',    :as => 'new_favorite'
  post '/favorites',         :controller => 'favorites', :action => 'create', :as => 'favorites'

  get '/favorites',          :controller => 'favorites', :action => 'index'
  get '/favorites/:id',      :controller => 'favorites', :action => 'show',   :as => 'favorite'

  get '/favorites/:id/edit', :controller => 'favorites', :action => 'edit',   :as => 'edit_favorite'
  patch '/favorites/:id',    :controller => 'favorites', :action => 'update'

  delete '/favorites/:id',   :controller => 'favorites', :action => 'destroy'

  get '/farms/new',      :controller => 'farms', :action => 'new',    :as => 'new_farm'
  post '/farms',         :controller => 'farms', :action => 'create', :as => 'farms'

  get '/farms',          :controller => 'farms', :action => 'index'
  get '/farms/:id',      :controller => 'farms', :action => 'show',   :as => 'farm'

  get '/farms/:id/edit', :controller => 'farms', :action => 'edit',   :as => 'edit_farm'
  patch '/farms/:id',    :controller => 'farms', :action => 'update'

  delete '/farms/:id',   :controller => 'farms', :action => 'destroy'

  get '/dishes/new',      :controller => 'dishes', :action => 'new',    :as => 'new_dish'
  post '/dishes',         :controller => 'dishes', :action => 'create', :as => 'dishes'

  get '/dishes',          :controller => 'dishes', :action => 'index'
  get '/dishes/:id',      :controller => 'dishes', :action => 'show',   :as => 'dish'

  get '/dishes/:id/edit', :controller => 'dishes', :action => 'edit',   :as => 'edit_dish'
  patch '/dishes/:id',    :controller => 'dishes', :action => 'update'

  delete '/dishes/:id',   :controller => 'dishes', :action => 'destroy'

  get '/restaurants/new',      :controller => 'restaurants', :action => 'new',    :as => 'new_restaurant'
  post '/restaurants',         :controller => 'restaurants', :action => 'create', :as => 'restaurants'

  get '/restaurants',          :controller => 'restaurants', :action => 'index'
  get '/restaurants/:id',      :controller => 'restaurants', :action => 'show',   :as => 'restaurant'

  get '/restaurants/:id/edit', :controller => 'restaurants', :action => 'edit',   :as => 'edit_restaurant'
  patch '/restaurants/:id',    :controller => 'restaurants', :action => 'update'

  delete '/restaurants/:id',   :controller => 'restaurants', :action => 'destroy'

  get '/consumers/new',      :controller => 'consumers', :action => 'new',    :as => 'new_consumer'
  post '/consumers',         :controller => 'consumers', :action => 'create', :as => 'consumers'

  get '/consumers',          :controller => 'consumers', :action => 'index'
  get '/consumers/:id',      :controller => 'consumers', :action => 'show',   :as => 'consumer'

  get '/consumers/:id/edit', :controller => 'consumers', :action => 'edit',   :as => 'edit_consumer'
  patch '/consumers/:id',    :controller => 'consumers', :action => 'update'

  delete '/consumers/:id',   :controller => 'consumers', :action => 'destroy'

end

app/models/farm.rb
class Farm < ActiveRecord::Base
  has_many :favorites
  has_many :restaurants
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  def index
    @farms = Farm.all
  end

  def show
    @farm = Farm.find(params[:id])
  end

  def new
    @farm = Farm.new
  end

  def create
    @farm = Farm.new
    @farm.name = params[:name]
    @farm.address = params[:address]
    @farm.website_url = params[:website_url]

    if @farm.save
      redirect_to farms_url, :notice => "Farm created successfully."
    else
      render 'new'
    end
  end

  def edit
    @farm = Farm.find(params[:id])
  end

  def update
    @farm = Farm.find(params[:id])

    @farm.name = params[:name]
    @farm.address = params[:address]
    @farm.website_url = params[:website_url]

    if @farm.save
      redirect_to farm_url(@farm.id), :notice => "Farm updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @farm = Farm.find(params[:id])

    @farm.destroy

    redirect_to farms_url, :notice => "Farm deleted."
  end
end

app/views/farms/edit.html.erb
<!-- Validation failure messages -->

<% if @farm.errors.any? %>
  <% @farm.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Farm #<%= @farm.id %></h3>
      </div>
      <div class="panel-body">
        <%= form_tag farm_url(@farm.id), :method => "patch", :class => "form-horizontal" do %>
          <!-- Label and input for name -->
          <div class="form-group">
            <label for="name" class="col-sm-2 control-label">
              Name
            </label>
            <div class="col-sm-10">
              <input type="text" id="name" name="name" placeholder="Name" class="form-control" value="<%= @farm.name %>">
            </div>
          </div>

          <!-- Label and input for address -->
          <div class="form-group">
            <label for="address" class="col-sm-2 control-label">
              Address
            </label>
            <div class="col-sm-10">
              <input type="text" id="address" name="address" placeholder="Address" class="form-control" value="<%= @farm.address %>">
            </div>
          </div>

          <!-- Label and input for website_url -->
          <div class="form-group">
            <label for="website_url" class="col-sm-2 control-label">
              Website url
            </label>
            <div class="col-sm-10">
              <input type="text" id="website_url" name="website_url" placeholder="Website url" class="form-control" value="<%= @farm.website_url %>">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Update Farm" class="btn btn-warning">
              or
              <%= link_to "Cancel", farm_url(@farm.id) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<!-- End responsive panel example -->

app/views/farms/index.html.erb
<div class="page-header">
  <h1>
    Farms
    <%= link_to new_farm_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Farms (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @farms.each do |farm| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Farm #<%= farm.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Name</dt>
          <dd><%= farm.name %></dd>

          <dt>Address</dt>
          <dd><%= farm.address %></dd>

          <dt>Website url</dt>
          <dd><%= farm.website_url %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to farm_url(farm), :class => "btn btn-primary" do %>
            <i class="fa fa-search-plus"></i>
          <% end %>
          <%= link_to edit_farm_url(farm), :class => "btn btn-warning" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to farm_url(farm), :method => "delete", :data => { :confirm => "Do you really want to delete this farm?" }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/farms/new.html.erb
<!-- Validation failure messages -->

<% if @farm.errors.any? %>
  <% @farm.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Farm</h3>
      </div>
      <div class="panel-body">
        <%= form_tag farms_url, :method => "post", :class => "form-horizontal" do %>
          <!-- Label and input for name -->
          <div class="form-group">
            <label for="name" class="col-sm-2 control-label">
              Name
            </label>
            <div class="col-sm-10">
              <input type="text" id="name" name="name" placeholder="Name" class="form-control" value="<%= @farm.name %>">
            </div>
          </div>

          <!-- Label and input for address -->
          <div class="form-group">
            <label for="address" class="col-sm-2 control-label">
              Address
            </label>
            <div class="col-sm-10">
              <input type="text" id="address" name="address" placeholder="Address" class="form-control" value="<%= @farm.address %>">
            </div>
          </div>

          <!-- Label and input for website_url -->
          <div class="form-group">
            <label for="website_url" class="col-sm-2 control-label">
              Website url
            </label>
            <div class="col-sm-10">
              <input type="text" id="website_url" name="website_url" placeholder="Website url" class="form-control" value="<%= @farm.website_url %>">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Create Farm" class="btn btn-success">
              or
              <a href="/farms">Cancel</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/farms/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Farm #<%= @farm.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Name</dt>
              <dd><%= @farm.name %></dd>

              <dt>Address</dt>
              <dd><%= @farm.address %></dd>

              <dt>Website url</dt>
              <dd><%= @farm.website_url %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to farms_url, :class => "btn btn-primary" do %>
                <i class="fa fa-chevron-left"></i>
              <% end %>
              <%= link_to edit_farm_url(@farm.id), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to farm_url(@farm.id), :method => "delete", :data => { :confirm => "Do you really want to delete this farm?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->