config/routes.rb
Rails.application.routes.draw do

  devise_for :consumers
  root to: "consumers#new"

  get '/favorites/new',      :controller => 'favorites', :action => 'new',    :as => 'new_favorite'
  post '/favorites',         :controller => 'favorites', :action => 'create', :as => 'favorites'

  get '/favorites',          :controller => 'favorites', :action => 'index'
  get '/favorites/:id',      :controller => 'favorites', :action => 'show',   :as => 'favorite'

  get '/favorites/:id/edit', :controller => 'favorites', :action => 'edit',   :as => 'edit_favorite'
  patch '/favorites/:id',    :controller => 'favorites', :action => 'update'

  delete '/favorites/:id',   :controller => 'favorites', :action => 'destroy'

  get '/farms/new',      :controller => 'farms', :action => 'new',    :as => 'new_farm'
  post '/farms',         :controller => 'farms', :action => 'create', :as => 'farms'

  get '/farms',          :controller => 'farms', :action => 'index'
  get '/farms/:id',      :controller => 'farms', :action => 'show',   :as => 'farm'

  get '/farms/:id/edit', :controller => 'farms', :action => 'edit',   :as => 'edit_farm'
  patch '/farms/:id',    :controller => 'farms', :action => 'update'

  delete '/farms/:id',   :controller => 'farms', :action => 'destroy'

  get '/dishes/new',      :controller => 'dishes', :action => 'new',    :as => 'new_dish'
  post '/dishes',         :controller => 'dishes', :action => 'create', :as => 'dishes'

  get '/dishes',          :controller => 'dishes', :action => 'index'
  get '/dishes/:id',      :controller => 'dishes', :action => 'show',   :as => 'dish'

  get '/dishes/:id/edit', :controller => 'dishes', :action => 'edit',   :as => 'edit_dish'
  patch '/dishes/:id',    :controller => 'dishes', :action => 'update'

  delete '/dishes/:id',   :controller => 'dishes', :action => 'destroy'

  get '/restaurants/new',      :controller => 'restaurants', :action => 'new',    :as => 'new_restaurant'
  post '/restaurants',         :controller => 'restaurants', :action => 'create', :as => 'restaurants'

  get '/restaurants',          :controller => 'restaurants', :action => 'index'
  get '/restaurants/:id',      :controller => 'restaurants', :action => 'show',   :as => 'restaurant'

  get '/restaurants/:id/edit', :controller => 'restaurants', :action => 'edit',   :as => 'edit_restaurant'
  patch '/restaurants/:id',    :controller => 'restaurants', :action => 'update'

  delete '/restaurants/:id',   :controller => 'restaurants', :action => 'destroy'

  get '/consumers/new',      :controller => 'consumers', :action => 'new',    :as => 'new_consumer'
  post '/consumers',         :controller => 'consumers', :action => 'create', :as => 'consumers'

  get '/consumers',          :controller => 'consumers', :action => 'index'
  get '/consumers/:id',      :controller => 'consumers', :action => 'show',   :as => 'consumer'

  get '/consumers/:id/edit', :controller => 'consumers', :action => 'edit',   :as => 'edit_consumer'
  patch '/consumers/:id',    :controller => 'consumers', :action => 'update'

  delete '/consumers/:id',   :controller => 'consumers', :action => 'destroy'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :consumer
  belongs_to :farm
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.all
  end

  def show
    @favorite = Favorite.find(params[:id])
  end

  def new
    @favorite = Favorite.new
  end

  def create
    @favorite = Favorite.new
    @favorite.consumer_id = params[:consumer_id]
    @favorite.farm_id = params[:farm_id]

    if @favorite.save
      redirect_to favorites_url, :notice => "Favorite created successfully."
    else
      render 'new'
    end
  end

  def edit
    @favorite = Favorite.find(params[:id])
  end

  def update
    @favorite = Favorite.find(params[:id])

    @favorite.consumer_id = params[:consumer_id]
    @favorite.farm_id = params[:farm_id]

    if @favorite.save
      redirect_to favorite_url(@favorite.id), :notice => "Favorite updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])

    @favorite.destroy

    redirect_to favorites_url, :notice => "Favorite deleted."
  end
end

app/views/favorites/edit.html.erb
<!-- Validation failure messages -->

<% if @favorite.errors.any? %>
  <% @favorite.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Favorite #<%= @favorite.id %></h3>
      </div>
      <div class="panel-body">
        <%= form_tag favorite_url(@favorite.id), :method => "patch", :class => "form-horizontal" do %>
          <!-- Label and input for consumer_id -->
          <div class="form-group">
            <label for="consumer_id" class="col-sm-2 control-label">
              Consumer
            </label>
            <div class="col-sm-10">
              <input type="text" id="consumer_id" name="consumer_id" placeholder="Consumer" class="form-control" value="<%= @favorite.consumer_id %>">
            </div>
          </div>

          <!-- Label and input for farm_id -->
          <div class="form-group">
            <label for="farm_id" class="col-sm-2 control-label">
              Farm
            </label>
            <div class="col-sm-10">
              <input type="text" id="farm_id" name="farm_id" placeholder="Farm" class="form-control" value="<%= @favorite.farm_id %>">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Update Favorite" class="btn btn-warning">
              or
              <%= link_to "Cancel", favorite_url(@favorite.id) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<!-- End responsive panel example -->

app/views/favorites/index.html.erb
<div class="page-header">
  <h1>
    Favorites
    <%= link_to new_favorite_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Favorites (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @favorites.each do |favorite| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Favorite #<%= favorite.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Consumer</dt>
          <dd><%= favorite.consumer_id %></dd>

          <dt>Farm</dt>
          <dd><%= favorite.farm_id %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to favorite_url(favorite), :class => "btn btn-primary" do %>
            <i class="fa fa-search-plus"></i>
          <% end %>
          <%= link_to edit_favorite_url(favorite), :class => "btn btn-warning" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to favorite_url(favorite), :method => "delete", :data => { :confirm => "Do you really want to delete this favorite?" }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/favorites/new.html.erb
<!-- Validation failure messages -->

<% if @favorite.errors.any? %>
  <% @favorite.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Favorite</h3>
      </div>
      <div class="panel-body">
        <%= form_tag favorites_url, :method => "post", :class => "form-horizontal" do %>
          <!-- Label and input for consumer_id -->
          <div class="form-group">
            <label for="consumer_id" class="col-sm-2 control-label">
              Consumer
            </label>
            <div class="col-sm-10">
              <input type="text" id="consumer_id" name="consumer_id" placeholder="Consumer" class="form-control" value="<%= @favorite.consumer_id %>">
            </div>
          </div>

          <!-- Label and input for farm_id -->
          <div class="form-group">
            <label for="farm_id" class="col-sm-2 control-label">
              Farm
            </label>
            <div class="col-sm-10">
              <input type="text" id="farm_id" name="farm_id" placeholder="Farm" class="form-control" value="<%= @favorite.farm_id %>">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Create Favorite" class="btn btn-success">
              or
              <a href="/favorites">Cancel</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/favorites/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Favorite #<%= @favorite.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Consumer</dt>
              <dd><%= @favorite.consumer_id %></dd>

              <dt>Farm</dt>
              <dd><%= @favorite.farm_id %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to favorites_url, :class => "btn btn-primary" do %>
                <i class="fa fa-chevron-left"></i>
              <% end %>
              <%= link_to edit_favorite_url(@favorite.id), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to favorite_url(@favorite.id), :method => "delete", :data => { :confirm => "Do you really want to delete this favorite?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->