config/routes.rb
Rails.application.routes.draw do

  devise_for :consumers
  root to: "consumers#new"

  get '/favorites/new',      :controller => 'favorites', :action => 'new',    :as => 'new_favorite'
  post '/favorites',         :controller => 'favorites', :action => 'create', :as => 'favorites'

  get '/favorites',          :controller => 'favorites', :action => 'index'
  get '/favorites/:id',      :controller => 'favorites', :action => 'show',   :as => 'favorite'

  get '/favorites/:id/edit', :controller => 'favorites', :action => 'edit',   :as => 'edit_favorite'
  patch '/favorites/:id',    :controller => 'favorites', :action => 'update'

  delete '/favorites/:id',   :controller => 'favorites', :action => 'destroy'

  get '/farms/new',      :controller => 'farms', :action => 'new',    :as => 'new_farm'
  post '/farms',         :controller => 'farms', :action => 'create', :as => 'farms'

  get '/farms',          :controller => 'farms', :action => 'index'
  get '/farms/:id',      :controller => 'farms', :action => 'show',   :as => 'farm'

  get '/farms/:id/edit', :controller => 'farms', :action => 'edit',   :as => 'edit_farm'
  patch '/farms/:id',    :controller => 'farms', :action => 'update'

  delete '/farms/:id',   :controller => 'farms', :action => 'destroy'

  get '/dishes/new',      :controller => 'dishes', :action => 'new',    :as => 'new_dish'
  post '/dishes',         :controller => 'dishes', :action => 'create', :as => 'dishes'

  get '/dishes',          :controller => 'dishes', :action => 'index'
  get '/dishes/:id',      :controller => 'dishes', :action => 'show',   :as => 'dish'

  get '/dishes/:id/edit', :controller => 'dishes', :action => 'edit',   :as => 'edit_dish'
  patch '/dishes/:id',    :controller => 'dishes', :action => 'update'

  delete '/dishes/:id',   :controller => 'dishes', :action => 'destroy'

  get '/restaurants/new',      :controller => 'restaurants', :action => 'new',    :as => 'new_restaurant'
  post '/restaurants',         :controller => 'restaurants', :action => 'create', :as => 'restaurants'

  get '/restaurants',          :controller => 'restaurants', :action => 'index'
  get '/restaurants/:id',      :controller => 'restaurants', :action => 'show',   :as => 'restaurant'

  get '/restaurants/:id/edit', :controller => 'restaurants', :action => 'edit',   :as => 'edit_restaurant'
  patch '/restaurants/:id',    :controller => 'restaurants', :action => 'update'

  delete '/restaurants/:id',   :controller => 'restaurants', :action => 'destroy'

  get '/consumers/new',      :controller => 'consumers', :action => 'new',    :as => 'new_consumer'
  post '/consumers',         :controller => 'consumers', :action => 'create', :as => 'consumers'

  get '/consumers',          :controller => 'consumers', :action => 'index'
  get '/consumers/:id',      :controller => 'consumers', :action => 'show',   :as => 'consumer'

  get '/consumers/:id/edit', :controller => 'consumers', :action => 'edit',   :as => 'edit_consumer'
  patch '/consumers/:id',    :controller => 'consumers', :action => 'update'

  delete '/consumers/:id',   :controller => 'consumers', :action => 'destroy'

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :restaurant
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def index
    @dishes = Dish.all
  end

  def show
    @dish = Dish.find(params[:id])
  end

  def new
    @dish = Dish.new
  end

  def create
    @dish = Dish.new
    @dish.restaurant_id = params[:restaurant_id]
    @dish.name = params[:name]
    @dish.desc = params[:desc]

    if @dish.save
      redirect_to dishes_url, :notice => "Dish created successfully."
    else
      render 'new'
    end
  end

  def edit
    @dish = Dish.find(params[:id])
  end

  def update
    @dish = Dish.find(params[:id])

    @dish.restaurant_id = params[:restaurant_id]
    @dish.name = params[:name]
    @dish.desc = params[:desc]

    if @dish.save
      redirect_to dish_url(@dish.id), :notice => "Dish updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @dish = Dish.find(params[:id])

    @dish.destroy

    redirect_to dishes_url, :notice => "Dish deleted."
  end
end

app/views/dishes/edit.html.erb
<!-- Validation failure messages -->

<% if @dish.errors.any? %>
  <% @dish.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Dish #<%= @dish.id %></h3>
      </div>
      <div class="panel-body">
        <%= form_tag dish_url(@dish.id), :method => "patch", :class => "form-horizontal" do %>
          <!-- Label and input for restaurant_id -->
          <div class="form-group">
            <label for="restaurant_id" class="col-sm-2 control-label">
              Restaurant
            </label>
            <div class="col-sm-10">
              <input type="text" id="restaurant_id" name="restaurant_id" placeholder="Restaurant" class="form-control" value="<%= @dish.restaurant_id %>">
            </div>
          </div>

          <!-- Label and input for name -->
          <div class="form-group">
            <label for="name" class="col-sm-2 control-label">
              Name
            </label>
            <div class="col-sm-10">
              <input type="text" id="name" name="name" placeholder="Name" class="form-control" value="<%= @dish.name %>">
            </div>
          </div>

          <!-- Label and input for desc -->
          <div class="form-group">
            <label for="desc" class="col-sm-2 control-label">
              Desc
            </label>
            <div class="col-sm-10">
              <textarea id="desc" name="desc" placeholder="Desc" class="form-control" rows="3"><%= @dish.desc %></textarea>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Update Dish" class="btn btn-warning">
              or
              <%= link_to "Cancel", dish_url(@dish.id) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<!-- End responsive panel example -->

app/views/dishes/index.html.erb
<div class="page-header">
  <h1>
    Dishes
    <%= link_to new_dish_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Dishes (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @dishes.each do |dish| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Dish #<%= dish.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Restaurant</dt>
          <dd><%= dish.restaurant_id %></dd>

          <dt>Name</dt>
          <dd><%= dish.name %></dd>

          <dt>Desc</dt>
          <dd><%= dish.desc %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to dish_url(dish), :class => "btn btn-primary" do %>
            <i class="fa fa-search-plus"></i>
          <% end %>
          <%= link_to edit_dish_url(dish), :class => "btn btn-warning" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to dish_url(dish), :method => "delete", :data => { :confirm => "Do you really want to delete this dish?" }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/dishes/new.html.erb
<!-- Validation failure messages -->

<% if @dish.errors.any? %>
  <% @dish.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Dish</h3>
      </div>
      <div class="panel-body">
        <%= form_tag dishes_url, :method => "post", :class => "form-horizontal" do %>
          <!-- Label and input for restaurant_id -->
          <div class="form-group">
            <label for="restaurant_id" class="col-sm-2 control-label">
              Restaurant
            </label>
            <div class="col-sm-10">
              <input type="text" id="restaurant_id" name="restaurant_id" placeholder="Restaurant" class="form-control" value="<%= @dish.restaurant_id %>">
            </div>
          </div>

          <!-- Label and input for name -->
          <div class="form-group">
            <label for="name" class="col-sm-2 control-label">
              Name
            </label>
            <div class="col-sm-10">
              <input type="text" id="name" name="name" placeholder="Name" class="form-control" value="<%= @dish.name %>">
            </div>
          </div>

          <!-- Label and input for desc -->
          <div class="form-group">
            <label for="desc" class="col-sm-2 control-label">
              Desc
            </label>
            <div class="col-sm-10">
              <textarea id="desc" name="desc" placeholder="Desc" class="form-control" rows="3"><%= @dish.desc %></textarea>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Create Dish" class="btn btn-success">
              or
              <a href="/dishes">Cancel</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/dishes/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Dish #<%= @dish.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Restaurant</dt>
              <dd><%= @dish.restaurant_id %></dd>

              <dt>Name</dt>
              <dd><%= @dish.name %></dd>

              <dt>Desc</dt>
              <dd><%= @dish.desc %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to dishes_url, :class => "btn btn-primary" do %>
                <i class="fa fa-chevron-left"></i>
              <% end %>
              <%= link_to edit_dish_url(@dish.id), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to dish_url(@dish.id), :method => "delete", :data => { :confirm => "Do you really want to delete this dish?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->